// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Shopify/sarama (interfaces: OffsetManager)

// Package kafka is a generated GoMock package.
package kafka

import (
	reflect "reflect"

	sarama "github.com/Shopify/sarama"
	gomock "github.com/golang/mock/gomock"
)

// MockOffsetManager is a mock of OffsetManager interface.
type MockOffsetManager struct {
	ctrl     *gomock.Controller
	recorder *MockOffsetManagerMockRecorder
}

// MockOffsetManagerMockRecorder is the mock recorder for MockOffsetManager.
type MockOffsetManagerMockRecorder struct {
	mock *MockOffsetManager
}

// NewMockOffsetManager creates a new mock instance.
func NewMockOffsetManager(ctrl *gomock.Controller) *MockOffsetManager {
	mock := &MockOffsetManager{ctrl: ctrl}
	mock.recorder = &MockOffsetManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOffsetManager) EXPECT() *MockOffsetManagerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockOffsetManager) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockOffsetManagerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockOffsetManager)(nil).Close))
}

// Commit mocks base method.
func (m *MockOffsetManager) Commit() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Commit")
}

// Commit indicates an expected call of Commit.
func (mr *MockOffsetManagerMockRecorder) Commit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockOffsetManager)(nil).Commit))
}

// ManagePartition mocks base method.
func (m *MockOffsetManager) ManagePartition(arg0 string, arg1 int32) (sarama.PartitionOffsetManager, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ManagePartition", arg0, arg1)
	ret0, _ := ret[0].(sarama.PartitionOffsetManager)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ManagePartition indicates an expected call of ManagePartition.
func (mr *MockOffsetManagerMockRecorder) ManagePartition(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ManagePartition", reflect.TypeOf((*MockOffsetManager)(nil).ManagePartition), arg0, arg1)
}
