// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Shopify/sarama (interfaces: PartitionOffsetManager)

// Package kafka is a generated GoMock package.
package kafka

import (
	reflect "reflect"

	sarama "github.com/Shopify/sarama"
	gomock "github.com/golang/mock/gomock"
)

// MockPartitionOffsetManager is a mock of PartitionOffsetManager interface.
type MockPartitionOffsetManager struct {
	ctrl     *gomock.Controller
	recorder *MockPartitionOffsetManagerMockRecorder
}

// MockPartitionOffsetManagerMockRecorder is the mock recorder for MockPartitionOffsetManager.
type MockPartitionOffsetManagerMockRecorder struct {
	mock *MockPartitionOffsetManager
}

// NewMockPartitionOffsetManager creates a new mock instance.
func NewMockPartitionOffsetManager(ctrl *gomock.Controller) *MockPartitionOffsetManager {
	mock := &MockPartitionOffsetManager{ctrl: ctrl}
	mock.recorder = &MockPartitionOffsetManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPartitionOffsetManager) EXPECT() *MockPartitionOffsetManagerMockRecorder {
	return m.recorder
}

// AsyncClose mocks base method.
func (m *MockPartitionOffsetManager) AsyncClose() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AsyncClose")
}

// AsyncClose indicates an expected call of AsyncClose.
func (mr *MockPartitionOffsetManagerMockRecorder) AsyncClose() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AsyncClose", reflect.TypeOf((*MockPartitionOffsetManager)(nil).AsyncClose))
}

// Close mocks base method.
func (m *MockPartitionOffsetManager) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockPartitionOffsetManagerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockPartitionOffsetManager)(nil).Close))
}

// Errors mocks base method.
func (m *MockPartitionOffsetManager) Errors() <-chan *sarama.ConsumerError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Errors")
	ret0, _ := ret[0].(<-chan *sarama.ConsumerError)
	return ret0
}

// Errors indicates an expected call of Errors.
func (mr *MockPartitionOffsetManagerMockRecorder) Errors() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Errors", reflect.TypeOf((*MockPartitionOffsetManager)(nil).Errors))
}

// MarkOffset mocks base method.
func (m *MockPartitionOffsetManager) MarkOffset(arg0 int64, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MarkOffset", arg0, arg1)
}

// MarkOffset indicates an expected call of MarkOffset.
func (mr *MockPartitionOffsetManagerMockRecorder) MarkOffset(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkOffset", reflect.TypeOf((*MockPartitionOffsetManager)(nil).MarkOffset), arg0, arg1)
}

// NextOffset mocks base method.
func (m *MockPartitionOffsetManager) NextOffset() (int64, string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextOffset")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(string)
	return ret0, ret1
}

// NextOffset indicates an expected call of NextOffset.
func (mr *MockPartitionOffsetManagerMockRecorder) NextOffset() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextOffset", reflect.TypeOf((*MockPartitionOffsetManager)(nil).NextOffset))
}

// ResetOffset mocks base method.
func (m *MockPartitionOffsetManager) ResetOffset(arg0 int64, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ResetOffset", arg0, arg1)
}

// ResetOffset indicates an expected call of ResetOffset.
func (mr *MockPartitionOffsetManagerMockRecorder) ResetOffset(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetOffset", reflect.TypeOf((*MockPartitionOffsetManager)(nil).ResetOffset), arg0, arg1)
}
